### ISSUE TITLE
"New issues" are not translate into Japanese.

### ISSUE THREAD

**Issue by loketable** [chiyama/workflow_graph#1]
"New issues" are not translate into Japanese.
Redmine の言語を日本語にして使用しているのですが、"New issues" のみ日本語に翻訳されません。
![image](https://user-images.githubusercontent.com/42633590/49501619-a9204200-f8b6-11e8-8605-565add9c8d10.png)

**Comment by chiyama** [comment]
こちらでも確認してみました。
何となく、edit.html.erb が悪さをしている予感がするので、調査・修正を進めてみます。

**Comment by chiyama** [comment]
問題を修正しました。ステータスリストを取得する際に、New issue だけハードコードしていたのが原因でした。

**Comment by loketable** [comment]
ご対応ありがとうございます:smile:
